# Generated by Codex on 2026-07-24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='membership',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'ACTIVE'),
                    ('expired', 'EXPIRED'),
                    ('canceled', 'CANCELED'),
                ],
                default='active',
                max_length=10,
            ),
        ),
    ]
