# Generated by Codex on 2026-07-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_duration_months_and_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='duration_months',
        ),
    ]
