# Generated by Django 6.0.7 on 2026-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_remove_membership_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='notify_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), models.Q(('expires_at__isnull', True), ('notify_at__isnull', True)), _connector='OR'), name='active_membership_requires_expiration_and_notify_at'),
        ),
    ]
