# Generated by Django 6.0.7 on 2026-07-28 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_membership_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='active_membership_requires_expiration_and_notify_at',
        ),
        migrations.AddField(
            model_name='membership',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 7, 28, 7, 51, 11, 184642, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='notify_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('notify_at__isnull', True), _connector='OR'), name='active_membership_requires_notify_at'),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='expires_at',
        ),
    ]
