# Generated by Django 6.0.7 on 2026-07-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_remove_membership_active_membership_requires_expiration_and_notify_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='active_membership_requires_notify_at',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('notify_at__isnull', False), _connector='OR'), name='active_membership_requires_notify_at'),
        ),
    ]
