# Generated by Django 6.0.7 on 2026-07-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_remove_membership_active_membership_requires_notify_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='active_membership_requires_notify_at',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'active'), ('notify_at__isnull', True), _connector='OR'), name='active_membership_requires_notify_at'),
        ),
    ]
