# Generated by Django 6.0.7 on 2026-07-28 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_remove_membership_active_membership_requires_notify_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='user',
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(default='9a6871a4-242d-4e97-96e8-e8ba111f37f2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('gym', 'user'), name='unique_membership_gym_user'),
        ),
    ]
