# Generated by Django 6.0.7 on 2026-07-17 21:12

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('primary_muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quadriceps', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('core', 'Core'), ('full_body', 'Full body')], max_length=255)),
                ('secondary_muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quadriceps', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('core', 'Core'), ('full_body', 'Full body')], max_length=255, null=True)),
                ('equipment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('none', 'No equipment'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('ez_bar', 'EZ bar'), ('trap_bar', 'Trap bar'), ('kettlebell', 'Kettlebell'), ('cable', 'Cable'), ('machine', 'Machine'), ('smith_machine', 'Smith machine'), ('resistance_band', 'Resistance band'), ('bench', 'Bench'), ('squat_rack', 'Squat rack'), ('pull_up_bar', 'Pull-up bar'), ('dip_bars', 'Dip bars'), ('suspension_trainer', 'Suspension trainer'), ('medicine_ball', 'Medicine ball'), ('exercise_ball', 'Exercise ball'), ('foam_roller', 'Foam roller'), ('cardio_machine', 'Cardio machine'), ('other', 'Other')], max_length=255))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
