# Generated by Django 6.0.7 on 2026-07-17 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscle_group',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscle_group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quadriceps', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('core', 'Core'), ('full_body', 'Full body')], max_length=255), default=['chest']),
            preserve_default=False,
        ),
    ]
