# Generated by Django 6.0.7 on 2026-07-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='reps',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
