# Generated by Django 6.0.7 on 2026-07-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutexercise_reps_workoutexercise_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programworkout',
            name='day',
            field=models.CharField(choices=[('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat'), ('SUN', 'Sun')], max_length=3),
        ),
    ]
